# Logit and temperature examples

## Softmax function properties

The function converts a list of values into probabilities but uses e^x

In [2]:
import numpy as np
def softmax(x):
    return np.exp(x) / np.sum(np.exp(x), axis=0)

a = np.array([1,2,3])
print(a)
print(softmax(a))
print(softmax(np.log(a))) 
print()
b=a*2
print(b)
print(softmax(b),' <- multiplication makes distribution "stronger"')
print(softmax(np.log(b)),' <- log maintains proportions (normalize)')
print()
c=a*0.5
print(c)
print(softmax(c),' <- division makes distribution "weaker"')
print(softmax(np.log(c)),' <- log maintains proportions')


[1 2 3]
[0.09003057 0.24472847 0.66524096]
[0.16666667 0.33333333 0.5       ]

[2 4 6]
[0.01587624 0.11731043 0.86681333]  <- multiplication makes distribution "stronger"
[0.16666667 0.33333333 0.5       ]  <- log maintains proportions (normalize)

[0.5 1.  1.5]
[0.18632372 0.30719589 0.50648039]  <- division makes distribution "weaker"
[0.16666667 0.33333333 0.5       ]  <- log maintains proportions


## Usage of tf.categorical

In [3]:
import tensorflow as tf
import numpy as np

# initial distrobution
a = np.array([[0,0.125,0.25,0.5]])
for i in range(6):
    print(a)
    # 30 numbers sampled using the given distribution
    x = tf.random.categorical(a, num_samples=30)
    # when numbers are bigger more '3' and less '0'
    print(x)
    a = a*2

[[0.    0.125 0.25  0.5  ]]
tf.Tensor([[1 0 3 1 3 2 0 1 3 2 3 0 3 0 1 3 3 0 3 2 0 2 1 2 3 3 3 2 2 0]], shape=(1, 30), dtype=int64)
[[0.   0.25 0.5  1.  ]]
tf.Tensor([[1 2 3 3 3 3 3 0 3 0 3 1 1 3 2 2 2 1 3 2 1 3 2 3 2 3 2 3 3 2]], shape=(1, 30), dtype=int64)
[[0.  0.5 1.  2. ]]
tf.Tensor([[2 2 3 2 1 2 3 3 2 2 3 3 2 3 3 3 1 3 3 3 3 3 3 3 2 3 2 3 3 2]], shape=(1, 30), dtype=int64)
[[0. 1. 2. 4.]]
tf.Tensor([[3 3 2 3 3 2 3 3 3 3 3 3 3 3 2 3 3 3 3 3 3 3 3 2 3 3 3 3 3 0]], shape=(1, 30), dtype=int64)
[[0. 2. 4. 8.]]
tf.Tensor([[3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 1 3 3 3 3 3 3 3 3 3]], shape=(1, 30), dtype=int64)
[[ 0.  4.  8. 16.]]
tf.Tensor([[3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3]], shape=(1, 30), dtype=int64)
