# NumPy arrays

In [2]:
import numpy as np

## Create arrays

In [2]:
np.full((2,2),7)

array([[7, 7],
       [7, 7]])

In [3]:
np.zeros((5,5,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [4]:
np.zeros((2,2,2),dtype=bool)

array([[[False, False],
        [False, False]],

       [[False, False],
        [False, False]]])

In [5]:
np.random.random((2,2))

array([[0.88876332, 0.07261563],
       [0.65516864, 0.29224776]])

## Array dimensions (shapes)

In [6]:
array1d = np.array([1,2,3,4,5,6,7,8,9,10])
array2d = np.array([[1,2,3,4,5],[6,7,8,9,10]])
array3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [7]:
print("1D\n",array1d)
print("shape",array1d.shape)

1D
 [ 1  2  3  4  5  6  7  8  9 10]
shape (10,)


In [8]:
print("2D\n",array2d)
print("shape",array2d.shape)

2D
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
shape (2, 5)


In [9]:
print("3D\n",array3d)
print("shape",array3d.shape)

3D
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
shape (2, 2, 3)


### When the number of elements does not match

In [10]:
a = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11]]]) # array with collections of different size
#np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11]]],dtype=object) # should use dtype
print(a)
print(a.shape)

[[list([1, 2, 3]) list([4, 5, 6])]
 [list([7, 8, 9]) list([10, 11])]]
(2, 2)


C:\Users\win\.conda\envs\abc\lib\site-packages\ipykernel_launcher.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  """Entry point for launching an IPython kernel.


### Random access by index

In [11]:
print("1D",array1d[1])
print("2D",array2d[1])
print("3D\n",array3d[1])

1D 2
2D [ 6  7  8  9 10]
3D
 [[ 7  8  9]
 [10 11 12]]


## Changing the shape of an array

### Transpose the matrix

In [12]:
array2d1 = np.array([[1],[2],[3],[4],[5],[6],[7],[8],[9],[10]])
print("array",array2d1,"-> shape",array2d1.shape)

array [[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]] -> shape (10, 1)


In [13]:
print(array2d1[1],"-> shape",array2d1[1].shape)

[2] -> shape (1,)


In [14]:
print(array2d1.T,'-> shape',array2d1.T.shape)

[[ 1  2  3  4  5  6  7  8  9 10]] -> shape (1, 10)


In [15]:
print(array2d1.T[0],'-> shape',array2d1.T[0].shape)

[ 1  2  3  4  5  6  7  8  9 10] -> shape (10,)


In [16]:
print(array2d1[1].T,'-> shape',array2d1[1].T.shape)

[2] -> shape (1,)


In [17]:
print(array2d1.T[0,1],'-> shape',array2d1.T[0,1].shape)

2 -> shape ()


### *reshape()* finction

In [3]:
a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(a,'\n',a.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] 
 (4, 3)


In [6]:
a.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [20]:
a.reshape(2,2,3)
#np.reshape(a,(2,2,3))

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [21]:
a.reshape(2,2,-1)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [22]:
a.reshape(-1,2,2)

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [23]:
a.reshape(1,-1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [24]:
a.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [25]:
a.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [26]:
a.reshape(-1,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [27]:
a.reshape(-1,1,1)

array([[[ 1]],

       [[ 2]],

       [[ 3]],

       [[ 4]],

       [[ 5]],

       [[ 6]],

       [[ 7]],

       [[ 8]],

       [[ 9]],

       [[10]],

       [[11]],

       [[12]]])

### Expand dimensions

In [28]:
print(a,'\n',a.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] 
 (4, 3)


In [29]:
x = np.expand_dims(a,axis=0)
print(x,'\n',x.shape)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]] 
 (1, 4, 3)


In [30]:
x = np.expand_dims(a,axis=1)
print(x,'\n',x.shape)

[[[ 1  2  3]]

 [[ 4  5  6]]

 [[ 7  8  9]]

 [[10 11 12]]] 
 (4, 1, 3)


## Slicing

In [31]:
a = np.array([[1,2,3],[8,5,7],[6,4,9]])
print(a,'shape=',a.shape)

[[1 2 3]
 [8 5 7]
 [6 4 9]] shape= (3, 3)


#### by index

In [32]:
a[:,0]

array([1, 8, 6])

In [33]:
a[0,:]

array([1, 2, 3])

In [34]:
a[0:2,1:]

array([[2, 3],
       [5, 7]])

In [35]:
a[:,1]

array([2, 5, 4])

#### by value

In [36]:
a[a<5]

array([1, 2, 3, 4])

#### Rows having value <5 in the second column [1]

In [37]:
a[a[:,1]<5]

array([[1, 2, 3],
       [6, 4, 9]])

#### Columns having value <6 in the second row [1]

In [38]:
a[:,a[1,:]<6]

array([[2],
       [5],
       [4]])

#### Two conditions with OR

In [39]:
a[(a[:,1]<5) | (a[:,0]<6)]

array([[1, 2, 3],
       [6, 4, 9]])

#### Two conditions with AND:

In [40]:
a[(a[:,1]<5) & (a[:,0]<6)]

array([[1, 2, 3]])

In [41]:
a<6

array([[ True,  True,  True],
       [False,  True, False],
       [False,  True, False]])

## Loading and saving arrays

#### no compression

In [42]:
array = np.arange(1,2500,1)
np.save('array',array)

In [43]:
new_array = np.load('array.npy')
print(new_array)

[   1    2    3 ... 2497 2498 2499]


#### with compression, multiple arrays

In [44]:
# two arrays
array = np.arange(1,2500,1)
array2 = np.ones((5,5))

np.savez_compressed('array',a0=array,a1=array2)

In [45]:
array_dict = np.load('array.npz')
print(array_dict)
for a in array_dict:
    print(a,array_dict[a])

a0 [   1    2    3 ... 2497 2498 2499]
a1 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


#### to text file

In [46]:
array = np.arange(1,2500,1)
np.savetxt('array',array)

In [47]:
new_array = np.loadtxt('array')
print(new_array)
array = new_array.astype(int)
print(array)

[1.000e+00 2.000e+00 3.000e+00 ... 2.497e+03 2.498e+03 2.499e+03]
[   1    2    3 ... 2497 2498 2499]


### 1D or 2D only!

In [48]:
array3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
np.savetxt('array',array3d) # ValueError: Expected 1D or 2D array, got 3D array instead

ValueError: Expected 1D or 2D array, got 3D array instead

## Operations on one array

### Simple operations

In [49]:
a = np.array([[1,2,3],[4,5,7],[6,8,9]])
a

array([[1, 2, 3],
       [4, 5, 7],
       [6, 8, 9]])

In [50]:
a/2

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3.5],
       [3. , 4. , 4.5]])

In [51]:
a+1

array([[ 2,  3,  4],
       [ 5,  6,  8],
       [ 7,  9, 10]])

In [52]:
np.sin(a)

array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427,  0.6569866 ],
       [-0.2794155 ,  0.98935825,  0.41211849]])

### Aggregations

In [53]:
b = np.array([[1,4,3],[7,5,2],[6,8,9]])
b

array([[1, 4, 3],
       [7, 5, 2],
       [6, 8, 9]])

In [54]:
np.sum(b)

45

In [55]:
np.max(b)

9

In [56]:
np.mean(b)

5.0

In [57]:
np.std(b)

2.581988897471611

In [58]:
b.sum(axis=1) # by rows

array([ 8, 14, 23])

In [59]:
b.sum(axis=0) # by columns

array([14, 17, 14])

**argmax()** - indexes of max values

In [60]:
b.argmax(axis=0)

array([1, 2, 2], dtype=int64)

In [61]:
b.argmax(axis=1)

array([1, 0, 2], dtype=int64)

## Operators on multiple arrays (broadcasting)

### Identical arrays

In [3]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[10,20,30],[40,50,60]])
print('a:\n',a)
print('b:\n',b)

a:
 [[1 2 3]
 [4 5 6]]
b:
 [[10 20 30]
 [40 50 60]]


In [4]:
a+b

array([[11, 22, 33],
       [44, 55, 66]])

In [64]:
a-b

array([[ -9, -18, -27],
       [-36, -45, -54]])

In [5]:
a*b

array([[ 10,  40,  90],
       [160, 250, 360]])

In [7]:
a@b.T #matrix multiplication!

array([[140, 320],
       [320, 770]])

### One array with dimension=1
- If the corresponding dimension is 1 the array is broadcasted
- The array *a[]* is broadcasted to all rows in *b[]*


In [66]:
a = np.array([1,2,3])
b = np.array([[10,20,30],[40,50,60]])
print('a:\n',a)
print('b:\n',b)

a:
 [1 2 3]
b:
 [[10 20 30]
 [40 50 60]]


In [67]:
a+b

array([[11, 22, 33],
       [41, 52, 63]])

In [68]:
a-b

array([[ -9, -18, -27],
       [-39, -48, -57]])

In [69]:
a*b

array([[ 10,  40,  90],
       [ 40, 100, 180]])

In [72]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([[4],[5],[6]])
#OR: c = b[:,None]
#OR: c = b[:,np.newaxis]

In [73]:
print('a',a.shape)
print('b',b.shape)
print('c',c.shape)

a (3,)
b (3,)
c (3, 1)


In [74]:
a+b

array([5, 7, 9])

In [75]:
a+c

array([[5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]])

### Incompatibile arrays

In [76]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[1,2],[3,4],[5,6]])

In [77]:
print('a',a.shape)
print('b',b.shape)

a (2, 3)
b (3, 2)


In [78]:
a+b # ValueError: operands could not be broadcast together with shapes (2,3) (3,2)

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

### Compatibile arrays

In [8]:
a = np.array([[1,2,3]])
b = np.array([[1],[3],[6]])

In [9]:
a

array([[1, 2, 3]])

In [10]:
b

array([[1],
       [3],
       [6]])

In [11]:
print('a shape: ',a.shape)
print('b shape: ',b.shape)

a shape:  (1, 3)
b shape:  (3, 1)


In [12]:
a+b

array([[2, 3, 4],
       [4, 5, 6],
       [7, 8, 9]])

In [91]:
a-b

array([[ 0,  1,  2],
       [-2, -1,  0],
       [-5, -4, -3]])

In [92]:
a*b

array([[ 1,  2,  3],
       [ 3,  6,  9],
       [ 6, 12, 18]])

In [15]:
a@b

array([[25]])

In [16]:
b@a

array([[ 1,  2,  3],
       [ 3,  6,  9],
       [ 6, 12, 18]])

In [95]:
a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
b = np.array([1,3,6])
print('a shape: ',a.shape)
print('b shape: ',b.shape)

a shape:  (4, 3)
b shape:  (3,)


In [94]:
a+b

array([[ 2,  5,  9],
       [ 5,  8, 12],
       [ 8, 11, 15],
       [11, 14, 18]])

## That's all