In [1]:
import numpy as np
import pandas as pd
import random
import tensorflow as tf
import matplotlib.pyplot as plt
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.metrics import confusion_matrix, accuracy_score
from tensorflow.keras.losses import categorical_crossentropy

In [2]:
def build_model():
    model = Sequential()
    model.add(Dense(4, input_dim=4, activation='sigmoid'))
    model.add(Dense(3, activation='sigmoid'))
    return model
model = build_model()
model.summary()


Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 4)                 20        
_________________________________________________________________
dense_1 (Dense)              (None, 3)                 15        
Total params: 35
Trainable params: 35
Non-trainable params: 0
_________________________________________________________________


In [3]:
data = pd.read_csv('iris.data')
print("Rows:",len(data))
print("Classes:",set(data['iris']))
samples = data.to_numpy()[:,:4] 
labels = data.to_numpy()[:,4]
samples = samples.astype(float)
from sklearn.preprocessing import LabelBinarizer
lb = LabelBinarizer()
labels = lb.fit_transform(labels)
print(labels.shape)
import sklearn.model_selection
(trainSamples, testSamples, trainLabels, testLabels) = sklearn.model_selection.train_test_split(samples, labels)
testSamples.shape

Rows: 150
Classes: {'Iris-virginica', 'Iris-versicolor', 'Iris-setosa'}
(150, 3)


(38, 4)

In [4]:
def step(tsamples, tlabels, verbose=1):
    with tf.GradientTape() as tape:
        predictions = model(tsamples)
        loss = categorical_crossentropy(tlabels,predictions)
    print("loss",loss.numpy().mean()) # mean loss across all samples
    # Calculate gradients
    gradients = tape.gradient(loss, model.trainable_variables)
    if verbose: 
        print('len',len(gradients))
        print('type',type(gradients))
        print('type[0]',type(gradients[0]))
        for j,g in enumerate(gradients):
            print(j,'shape',g.shape)
    opt.apply_gradients(zip(gradients, model.trainable_variables))


In [5]:
build_model()

opt = tf.keras.optimizers.Adam() # default learning_rate=0.001
#opt = tf.keras.optimizers.Adam(learning_rate=0.05, decay=0.01)

step_no=0

EPOCHS = 10
for i in range(EPOCHS):
    print('=========== STEP ',step_no)
    step_no+=1
    step(trainSamples,trainLabels,verbose=0)
    testResults = model.predict(testSamples)
    print(confusion_matrix(testLabels.argmax(axis=1), testResults.argmax(axis=1)))
    accuracy = accuracy_score(testLabels.argmax(axis=1), testResults.argmax(axis=1))
    print(f'Accuracy: {accuracy:.2f}')

=========== STEP  0
loss 1.2012441
[[11  0  0]
 [17  0  0]
 [10  0  0]]
Accuracy: 0.29
=========== STEP  1
loss 1.1999258
[[11  0  0]
 [17  0  0]
 [10  0  0]]
Accuracy: 0.29
=========== STEP  2
loss 1.1986192
[[11  0  0]
 [17  0  0]
 [10  0  0]]
Accuracy: 0.29
=========== STEP  3
loss 1.1973245
[[11  0  0]
 [17  0  0]
 [10  0  0]]
Accuracy: 0.29
=========== STEP  4
loss 1.1960415
[[11  0  0]
 [17  0  0]
 [10  0  0]]
Accuracy: 0.29
=========== STEP  5
loss 1.1947705
[[11  0  0]
 [17  0  0]
 [10  0  0]]
Accuracy: 0.29
=========== STEP  6
loss 1.1935111
[[11  0  0]
 [17  0  0]
 [10  0  0]]
Accuracy: 0.29
=========== STEP  7
loss 1.1922632
[[11  0  0]
 [17  0  0]
 [10  0  0]]
Accuracy: 0.29
=========== STEP  8
loss 1.1910261
[[11  0  0]
 [17  0  0]
 [10  0  0]]
Accuracy: 0.29
=========== STEP  9
loss 1.1897993
[[11  0  0]
 [17  0  0]
 [10  0  0]]
Accuracy: 0.29
