In [2]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
import pandas as pd
import numpy as np
import sklearn
import tensorflow as tf
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, cohen_kappa_score

## Build the network (model)

In [17]:
model = Sequential()
model.add(Dense(50, input_dim=4, activation='sigmoid'))
model.add(Dense(50, activation='sigmoid'))
model.add(Dense(1, activation='sigmoid'))
##model.add(Dense(1))
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_3 (Dense)              (None, 50)                250       
_________________________________________________________________
dense_4 (Dense)              (None, 50)                2550      
_________________________________________________________________
dense_5 (Dense)              (None, 1)                 51        
Total params: 2,851
Trainable params: 2,851
Non-trainable params: 0
_________________________________________________________________


## Load data (and remove one class)

In [4]:
data = pd.read_csv('iris.data')
print("Rows:",len(data))
data = data.drop(data[data.iris=='Iris-virginica'].index)
print("Rows after removal of 'Iris-virginica':",len(data))

Rows: 150
Rows after removal of 'Iris-virginica': 100


## Prepare samples and labels

In [5]:
print("Classes:",set(data['iris']))
samples = data.to_numpy()[:,:4]
samples = samples.astype(float)
labels = data.to_numpy()[:,4]

labels[labels[:]=='Iris-versicolor']=0
labels[labels[:]=='Iris-setosa']=1
#labels[labels[:]=='Iris-virginica']=2
labels = labels.astype(float)
print("Classes after renaming:",set(labels))

print("Samples:",samples.shape)
print("Labels:",labels.shape)


Classes: {'Iris-versicolor', 'Iris-setosa'}
Classes after renaming: {0.0, 1.0}
Samples: (100, 4)
Labels: (100,)


## Compile and fit model

In [6]:
import sklearn.model_selection
(trainSamples, testSamples, trainLabels, testLabels) = sklearn.model_selection.train_test_split(samples, labels, random_state=1)

model.compile(loss='binary_crossentropy', optimizer="adam",metrics=['accuracy'])

In [7]:
H = model.fit(trainSamples, trainLabels, epochs=40,batch_size=10)    

Epoch 1/40
8/8 [==============================] - 0s 880us/step - loss: 0.6947 - accuracy: 0.5333
Epoch 2/40
8/8 [==============================] - 0s 750us/step - loss: 0.6784 - accuracy: 0.5467
Epoch 3/40
8/8 [==============================] - 0s 750us/step - loss: 0.6705 - accuracy: 0.9333
Epoch 4/40
8/8 [==============================] - 0s 1ms/step - loss: 0.6531 - accuracy: 0.9733
Epoch 5/40
8/8 [==============================] - 0s 1ms/step - loss: 0.6385 - accuracy: 0.7333
Epoch 6/40
8/8 [==============================] - 0s 999us/step - loss: 0.6266 - accuracy: 0.6267
Epoch 7/40
8/8 [==============================] - 0s 1000us/step - loss: 0.6102 - accuracy: 0.7867
Epoch 8/40
8/8 [==============================] - 0s 1000us/step - loss: 0.5920 - accuracy: 0.9600
Epoch 9/40
8/8 [==============================] - 0s 999us/step - loss: 0.5747 - accuracy: 0.9467
Epoch 10/40
8/8 [==============================] - 0s 996us/step - loss: 0.5532 - accuracy: 0.9600
Epoch 11/40
8/8 [====

## Evaluate model

In [8]:
testResults = model.predict(testSamples)
print(testResults.T)
testResults = (testResults*2).astype(dtype=int) #conversion to (0,1)
print(testResults.T)
print(confusion_matrix(testLabels, testResults))
print(classification_report(testLabels, testResults))
print("Cohen's Kappa: {}".format(cohen_kappa_score(testLabels, testResults)))
print("Accuracy: ",accuracy_score(testLabels, testResults))


[[0.0545657  0.03043625 0.9816704  0.06678402 0.09936816 0.96699595
  0.9733919  0.05569908 0.05266124 0.03783125 0.04681817 0.9633428
  0.02854529 0.0236502  0.03404835 0.98010814 0.95450854 0.94450945
  0.02871946 0.9711163  0.9665257  0.02820253 0.03933173 0.04271343
  0.9705256 ]]
[[0 0 1 0 0 1 1 0 0 0 0 1 0 0 0 1 1 1 0 1 1 0 0 0 1]]
[[15  0]
 [ 0 10]]
              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00        15
         1.0       1.00      1.00      1.00        10

    accuracy                           1.00        25
   macro avg       1.00      1.00      1.00        25
weighted avg       1.00      1.00      1.00        25

Cohen's Kappa: 1.0
Accuracy:  1.0


# Dataset with three classes

In [29]:
data = pd.read_csv('iris.data')
print("Rows:",len(data))
print("Classes:",set(data['iris']))
samples = data.to_numpy()[:,:4] 
labels = data.to_numpy()[:,4]
samples = samples.astype(float)

labels[labels[:]=='Iris-versicolor']=0
labels[labels[:]=='Iris-setosa']=1
labels[labels[:]=='Iris-virginica']=2
labels = labels.astype(float)

print("Samples:",samples.shape)
print("Labels:",labels.shape)

Rows: 150
Classes: {'Iris-versicolor', 'Iris-setosa', 'Iris-virginica'}
Samples: (150, 4)
Labels: (150,)


In [30]:
import sklearn.model_selection
(trainSamples, testSamples, trainLabels, testLabels) = sklearn.model_selection.train_test_split(samples, labels)

In [20]:
#model.compile(loss='binary_crossentropy', optimizer="adam",metrics=['accuracy'])
#model.compile(loss='sparse_categorical_crossentropy', optimizer="adam",metrics=['accuracy'])
model.compile(loss='categorical_crossentropy', optimizer="adam",metrics=['accuracy'])

In [21]:
H = model.fit(trainSamples, trainLabels, epochs=10,batch_size=10)    

Epoch 1/10
12/12 [==============================] - 0s 1ms/step - loss: 1.1814e-07 - accuracy: 0.3393
Epoch 2/10
12/12 [==============================] - 0s 916us/step - loss: 1.1814e-07 - accuracy: 0.3393
Epoch 3/10
12/12 [==============================] - 0s 960us/step - loss: 1.1814e-07 - accuracy: 0.3393
Epoch 4/10
12/12 [==============================] - 0s 1ms/step - loss: 1.1814e-07 - accuracy: 0.3393
Epoch 5/10
12/12 [==============================] - 0s 999us/step - loss: 1.1814e-07 - accuracy: 0.3393
Epoch 6/10
12/12 [==============================] - 0s 1ms/step - loss: 1.1814e-07 - accuracy: 0.3393
Epoch 7/10
12/12 [==============================] - 0s 1ms/step - loss: 1.1814e-07 - accuracy: 0.3393
Epoch 8/10
12/12 [==============================] - 0s 1ms/step - loss: 1.1814e-07 - accuracy: 0.3393
Epoch 9/10
12/12 [==============================] - 0s 917us/step - loss: 1.1814e-07 - accuracy: 0.3393
Epoch 10/10
12/12 [==============================] - 0s 1000us/step - loss

## Evaluate model

In [22]:
testResults = model.predict(testSamples)
testResults = (testResults*2).astype(dtype=int) #conversion to (0,1)
print(testResults.T)
print(confusion_matrix(testLabels, testResults))
print(classification_report(testLabels, testResults))
print("Cohen's Kappa: {}".format(cohen_kappa_score(testLabels, testResults)))
print("Accuracy: ",accuracy_score(testLabels, testResults))

[[-3 -3 -3 -3 -3 -3 -3 -3 -3 -3 -3 -3 -3 -3 -3 -3 -3 -3 -3 -3 -3 -3 -3 -3
  -3 -3 -3 -3 -3 -3 -3 -3 -3 -3 -3 -3 -3 -3]]
[[ 0  0  0  0]
 [12  0  0  0]
 [13  0  0  0]
 [13  0  0  0]]
              precision    recall  f1-score   support

        -3.0       0.00      0.00      0.00       0.0
         0.0       0.00      0.00      0.00      12.0
         1.0       0.00      0.00      0.00      13.0
         2.0       0.00      0.00      0.00      13.0

    accuracy                           0.00      38.0
   macro avg       0.00      0.00      0.00      38.0
weighted avg       0.00      0.00      0.00      38.0

Cohen's Kappa: 0.0
Accuracy:  0.0


C:\programs\miniconda3\envs\deep\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


What is the problem?
The output is a number - no way that ANN learns the proper output!

## Change to one-hot encoding

In [31]:
print(labels.shape)
labels = tf.keras.utils.to_categorical(labels)

(150,)


In [32]:
print(labels)

[[0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1.

## New model (output: vector of 3 values)

In [33]:
model = Sequential()
model.add(Dense(50, input_dim=4, activation='sigmoid'))
model.add(Dense(50, activation='sigmoid'))
#model.add(Dense(1, activation='sigmoid'))
#model.add(Dense(3, activation='sigmoid')) # three values
model.add(Dense(3, activation='softmax')) # three values and normalization (output sums to 1)

model.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_9 (Dense)              (None, 50)                250       
_________________________________________________________________
dense_10 (Dense)             (None, 50)                2550      
_________________________________________________________________
dense_11 (Dense)             (None, 3)                 153       
Total params: 2,953
Trainable params: 2,953
Non-trainable params: 0
_________________________________________________________________


### Train model

In [34]:
(trainSamples, testSamples, trainLabels, testLabels) = sklearn.model_selection.train_test_split(samples, labels, random_state=1)
#model.compile(loss='binary_crossentropy', optimizer="adam",metrics=['accuracy'])
model.compile(loss='categorical_crossentropy', optimizer="adam",metrics=['accuracy'])

In [40]:
H = model.fit(trainSamples, trainLabels, epochs=10,batch_size=10, validation_data=(testSamples,testLabels))    

Epoch 1/10
12/12 [==============================] - 0s 4ms/step - loss: 0.2916 - accuracy: 0.9732 - val_loss: 0.2983 - val_accuracy: 0.9737
Epoch 2/10
12/12 [==============================] - 0s 2ms/step - loss: 0.2834 - accuracy: 0.9643 - val_loss: 0.3068 - val_accuracy: 0.9737
Epoch 3/10
12/12 [==============================] - 0s 2ms/step - loss: 0.2828 - accuracy: 0.9464 - val_loss: 0.3056 - val_accuracy: 0.9737
Epoch 4/10
12/12 [==============================] - 0s 2ms/step - loss: 0.2709 - accuracy: 0.9643 - val_loss: 0.2586 - val_accuracy: 0.9737
Epoch 5/10
12/12 [==============================] - 0s 2ms/step - loss: 0.2657 - accuracy: 0.9732 - val_loss: 0.2685 - val_accuracy: 0.9737
Epoch 6/10
12/12 [==============================] - 0s 2ms/step - loss: 0.2557 - accuracy: 0.9732 - val_loss: 0.2441 - val_accuracy: 0.9737
Epoch 7/10
12/12 [==============================] - 0s 2ms/step - loss: 0.2497 - accuracy: 0.9732 - val_loss: 0.2564 - val_accuracy: 0.9737
Epoch 8/10
12/12 [==

### Evaluate model (it is one-hot encoded!)

In [41]:
testResults = model.predict(testSamples)
print(testResults)
print(testResults.argmax(axis=1))

print(confusion_matrix(testLabels.argmax(axis=1), testResults.argmax(axis=1)))
print(classification_report(testLabels.argmax(axis=1), testResults.argmax(axis=1)))
print("Cohen's Kappa: {}".format(cohen_kappa_score(testLabels.argmax(axis=1), testResults.argmax(axis=1))))
print("Accuracy: ",accuracy_score(testLabels.argmax(axis=1), testResults.argmax(axis=1)))


[[2.38383319e-02 9.76059556e-01 1.02132624e-04]
 [7.39345551e-01 2.26482570e-01 3.41719314e-02]
 [7.51825511e-01 4.69974726e-02 2.01177016e-01]
 [3.03408429e-02 9.69520092e-01 1.38990741e-04]
 [2.03958839e-01 2.70253909e-03 7.93338537e-01]
 [6.36820376e-01 2.60191709e-02 3.37160438e-01]
 [2.55525082e-01 3.91506776e-03 7.40559757e-01]
 [5.09643704e-02 9.48765635e-01 2.70026154e-04]
 [5.05072474e-02 9.49238241e-01 2.54531275e-04]
 [1.63960531e-01 1.90465676e-03 8.34134817e-01]
 [7.32738137e-01 4.05409262e-02 2.26720944e-01]
 [3.94790098e-02 9.60326791e-01 1.94269218e-04]
 [1.61174431e-01 1.81117898e-03 8.37014437e-01]
 [7.18133450e-01 3.93196866e-02 2.42546886e-01]
 [6.39053941e-01 2.51813252e-02 3.35764706e-01]
 [4.14355360e-02 9.58366871e-01 1.97606612e-04]
 [7.89292753e-01 6.20503761e-02 1.48656845e-01]
 [6.30324543e-01 2.46822089e-02 3.44993204e-01]
 [4.47748341e-02 9.55002606e-01 2.22549716e-04]
 [3.58956568e-02 9.63940144e-01 1.64195342e-04]
 [6.92520857e-01 3.13148573e-02 2.761642

In [43]:
sample = [[1,2,3,4]]
pred = model.predict(sample)
print(sample,'->',pred)

pred = model.predict(testSamples[10:14])
for p,t in zip(pred[0:4],testLabels[10:14]):
    print(p,"->",t)


[[1, 2, 3, 4]] -> [[8.3436325e-02 7.0578331e-04 9.1585791e-01]]
[0.73273814 0.04054093 0.22672094] -> [1. 0. 0.]
[3.9479010e-02 9.6032679e-01 1.9426922e-04] -> [0. 1. 0.]
[0.16117443 0.00181118 0.83701444] -> [0. 0. 1.]
[0.71813345 0.03931969 0.24254689] -> [1. 0. 0.]


In [12]:
model.save('iris.h5')