In [1]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
import pandas as pd
import numpy as np
import sklearn
import tensorflow as tf
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, cohen_kappa_score

## Build the network (model)

In [2]:
model = Sequential()
model.add(Dense(50, input_dim=4, activation='sigmoid'))
model.add(Dense(50, activation='sigmoid'))
model.add(Dense(1, activation='sigmoid'))
#model.add(Dense(1))
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 50)                250       
_________________________________________________________________
dense_1 (Dense)              (None, 50)                2550      
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 51        
Total params: 2,851
Trainable params: 2,851
Non-trainable params: 0
_________________________________________________________________


## Load data (and remove one class)

In [3]:
data = pd.read_csv('iris.data')
print("Rows:",len(data))
data = data.drop(data[data.iris=='Iris-virginica'].index)
print("Rows after removal of 'Iris-virginica':",len(data))

Rows: 150
Rows after removal of 'Iris-virginica': 100


## Prepare samples and labels

In [4]:
print("Classes:",set(data['iris']))
samples = data.to_numpy()[:,:4]
samples = samples.astype(float)
labels = data.to_numpy()[:,4]

labels[labels[:]=='Iris-versicolor']=0
labels[labels[:]=='Iris-setosa']=1
#labels[labels[:]=='Iris-virginica']=2
labels = labels.astype(float)
print("Classes after renaming:",set(labels))

print("Samples:",samples.shape)
print("Labels:",labels.shape)


Classes: {'Iris-versicolor', 'Iris-setosa'}
Classes after renaming: {0.0, 1.0}
Samples: (100, 4)
Labels: (100,)


## Compile and fit model

In [5]:
import sklearn.model_selection
(trainSamples, testSamples, trainLabels, testLabels) = sklearn.model_selection.train_test_split(samples, labels, random_state=1)

model.compile(loss='binary_crossentropy', optimizer="adam",metrics=['accuracy'])

In [6]:
H = model.fit(trainSamples, trainLabels, epochs=40,batch_size=10)    

Epoch 1/40
8/8 [==============================] - 0s 0s/step - loss: 0.8345 - accuracy: 0.4667
Epoch 2/40
8/8 [==============================] - 0s 0s/step - loss: 0.7202 - accuracy: 0.4667
Epoch 3/40
8/8 [==============================] - 0s 2ms/step - loss: 0.6948 - accuracy: 0.4400
Epoch 4/40
8/8 [==============================] - 0s 1ms/step - loss: 0.6755 - accuracy: 0.5333
Epoch 5/40
8/8 [==============================] - 0s 871us/step - loss: 0.6647 - accuracy: 0.5467
Epoch 6/40
8/8 [==============================] - 0s 1ms/step - loss: 0.6513 - accuracy: 0.9867
Epoch 7/40
8/8 [==============================] - 0s 1ms/step - loss: 0.6401 - accuracy: 1.0000
Epoch 8/40
8/8 [==============================] - 0s 1ms/step - loss: 0.6277 - accuracy: 1.0000
Epoch 9/40
8/8 [==============================] - 0s 875us/step - loss: 0.6144 - accuracy: 1.0000
Epoch 10/40
8/8 [==============================] - 0s 875us/step - loss: 0.6005 - accuracy: 1.0000
Epoch 11/40
8/8 [==================

## Evaluate model

In [7]:
testResults = model.predict(testSamples)
print(testResults.T)
testResults = np.where(np.array(testResults) >= 0.5,1, 0) #conversion to (0,1)
print(testResults.T)
print(confusion_matrix(testLabels, testResults))
print(classification_report(testLabels, testResults))
print("Cohen's Kappa: {}".format(cohen_kappa_score(testLabels, testResults)))
print("Accuracy: ",accuracy_score(testLabels, testResults))


[[0.08033431 0.04314747 0.95484364 0.09771428 0.13670972 0.93077147
  0.94171804 0.07977754 0.07769758 0.05428568 0.06858394 0.92679757
  0.04012391 0.03452319 0.0482105  0.9527812  0.9116585  0.897305
  0.04132044 0.9378116  0.93171155 0.04282522 0.05728498 0.06618777
  0.93571883]]
[[0 0 1 0 0 1 1 0 0 0 0 1 0 0 0 1 1 1 0 1 1 0 0 0 1]]
[[15  0]
 [ 0 10]]
              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00        15
         1.0       1.00      1.00      1.00        10

    accuracy                           1.00        25
   macro avg       1.00      1.00      1.00        25
weighted avg       1.00      1.00      1.00        25

Cohen's Kappa: 1.0
Accuracy:  1.0


# Dataset with three classes

In [118]:
data = pd.read_csv('iris.data')
print("Rows:",len(data))
print("Classes:",set(data['iris']))
samples = data.to_numpy()[:,:4] 
labels = data.to_numpy()[:,4]
samples = samples.astype(float)

labels[labels[:]=='Iris-versicolor']=0
labels[labels[:]=='Iris-setosa']=1
labels[labels[:]=='Iris-virginica']=2
labels = labels.astype(float)

print("Samples:",samples.shape)
print("Labels:",labels.shape)

Rows: 150
Classes: {'Iris-versicolor', 'Iris-setosa', 'Iris-virginica'}
Samples: (150, 4)
Labels: (150,)


In [119]:
import sklearn.model_selection
(trainSamples, testSamples, trainLabels, testLabels) = sklearn.model_selection.train_test_split(samples, labels)

In [120]:
#model.compile(loss='binary_crossentropy', optimizer="adam",metrics=['accuracy'])
#model.compile(loss='sparse_categorical_crossentropy', optimizer="adam",metrics=['accuracy'])
model.compile(loss='categorical_crossentropy', optimizer="adam",metrics=['accuracy'])

In [122]:
H = model.fit(trainSamples, trainLabels, epochs=10,batch_size=10)    

Epoch 1/10
12/12 [==============================] - 0s 1ms/step - loss: 1.2027e-07 - accuracy: 0.3482
Epoch 2/10
12/12 [==============================] - 0s 1ms/step - loss: 1.2027e-07 - accuracy: 0.3482
Epoch 3/10
12/12 [==============================] - 0s 1ms/step - loss: 1.2027e-07 - accuracy: 0.3482
Epoch 4/10
12/12 [==============================] - 0s 1ms/step - loss: 1.2027e-07 - accuracy: 0.3482
Epoch 5/10
12/12 [==============================] - 0s 1ms/step - loss: 1.2027e-07 - accuracy: 0.3482
Epoch 6/10
12/12 [==============================] - 0s 1ms/step - loss: 1.2027e-07 - accuracy: 0.3482
Epoch 7/10
12/12 [==============================] - 0s 1ms/step - loss: 1.2027e-07 - accuracy: 0.3482
Epoch 8/10
12/12 [==============================] - 0s 1ms/step - loss: 1.2027e-07 - accuracy: 0.3482
Epoch 9/10
12/12 [==============================] - 0s 916us/step - loss: 1.2027e-07 - accuracy: 0.3482
Epoch 10/10
12/12 [==============================] - 0s 1000us/step - loss: 1.20

## Evaluate model

In [124]:
testResults = model.predict(testSamples)
testResults = (testResults*2).astype(dtype=int) #conversion to (0,1)
print(testResults.T)
print(confusion_matrix(testLabels, testResults))
print(classification_report(testLabels, testResults))
print("Cohen's Kappa: {}".format(cohen_kappa_score(testLabels, testResults)))
print("Accuracy: ",accuracy_score(testLabels, testResults))

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0]]
[[11  0  0]
 [17  0  0]
 [10  0  0]]
              precision    recall  f1-score   support

         0.0       0.29      1.00      0.45        11
         1.0       0.00      0.00      0.00        17
         2.0       0.00      0.00      0.00        10

    accuracy                           0.29        38
   macro avg       0.10      0.33      0.15        38
weighted avg       0.08      0.29      0.13        38

Cohen's Kappa: 0.0
Accuracy:  0.2894736842105263


What is the problem?
The output is a number - no way that ANN learns the proper output!

## Change to one-hot encoding

In [125]:
print(labels.shape)
labels = tf.keras.utils.to_categorical(labels)

(150,)


In [126]:
print(labels)

[[0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1.

## New model (output: vector of 3 values)

In [127]:
model = Sequential()
model.add(Dense(50, input_dim=4, activation='sigmoid'))
model.add(Dense(50, activation='sigmoid'))
#model.add(Dense(1, activation='sigmoid'))
#model.add(Dense(3, activation='sigmoid')) # three values
model.add(Dense(3, activation='softmax')) # three values and normalization (output sums to 1)

model.summary()

Model: "sequential_14"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_42 (Dense)             (None, 50)                250       
_________________________________________________________________
dense_43 (Dense)             (None, 50)                2550      
_________________________________________________________________
dense_44 (Dense)             (None, 3)                 153       
Total params: 2,953
Trainable params: 2,953
Non-trainable params: 0
_________________________________________________________________


### Train model

In [128]:
(trainSamples, testSamples, trainLabels, testLabels) = sklearn.model_selection.train_test_split(samples, labels, random_state=1)
#model.compile(loss='binary_crossentropy', optimizer="adam",metrics=['accuracy'])
model.compile(loss='categorical_crossentropy', optimizer="adam",metrics=['accuracy'])

In [132]:
H = model.fit(trainSamples, trainLabels, epochs=10,batch_size=10, validation_data=(testSamples,testLabels))    

Epoch 1/10
12/12 [==============================] - 0s 5ms/step - loss: 0.4244 - accuracy: 0.8750 - val_loss: 0.4391 - val_accuracy: 0.8684
Epoch 2/10
12/12 [==============================] - 0s 2ms/step - loss: 0.4116 - accuracy: 0.9375 - val_loss: 0.4140 - val_accuracy: 0.9737
Epoch 3/10
12/12 [==============================] - 0s 2ms/step - loss: 0.4031 - accuracy: 0.9643 - val_loss: 0.4048 - val_accuracy: 0.9737
Epoch 4/10
12/12 [==============================] - 0s 2ms/step - loss: 0.3910 - accuracy: 0.9643 - val_loss: 0.3954 - val_accuracy: 0.9737
Epoch 5/10
12/12 [==============================] - 0s 2ms/step - loss: 0.3814 - accuracy: 0.9375 - val_loss: 0.3949 - val_accuracy: 0.9737
Epoch 6/10
12/12 [==============================] - 0s 3ms/step - loss: 0.3710 - accuracy: 0.9643 - val_loss: 0.3716 - val_accuracy: 0.9737
Epoch 7/10
12/12 [==============================] - 0s 3ms/step - loss: 0.3649 - accuracy: 0.9643 - val_loss: 0.3585 - val_accuracy: 0.9737
Epoch 8/10
12/12 [==

### Evaluate model (it is one-hot encoded!)

In [134]:
testResults = model.predict(testSamples)
print(testResults)
print(testResults.argmax(axis=1))

print(confusion_matrix(testLabels.argmax(axis=1), testResults.argmax(axis=1)))
print(classification_report(testLabels.argmax(axis=1), testResults.argmax(axis=1)))
print("Cohen's Kappa: {}".format(cohen_kappa_score(testLabels.argmax(axis=1), testResults.argmax(axis=1))))
print("Accuracy: ",accuracy_score(testLabels.argmax(axis=1), testResults.argmax(axis=1)))


[[3.1715456e-02 9.6760398e-01 6.8052724e-04]
 [6.4117455e-01 2.3931405e-01 1.1951135e-01]
 [6.1207223e-01 6.1629355e-02 3.2629842e-01]
 [4.0520120e-02 9.5851302e-01 9.6682331e-04]
 [3.0384314e-01 8.6544352e-03 6.8750238e-01]
 [5.4404843e-01 3.9496783e-02 4.1645470e-01]
 [3.3872056e-01 1.1110156e-02 6.5016931e-01]
 [6.8333514e-02 9.2965460e-01 2.0119210e-03]
 [6.7647591e-02 9.3041712e-01 1.9353941e-03]
 [2.7380857e-01 7.0889760e-03 7.1910250e-01]
 [5.9663814e-01 5.5134047e-02 3.4822789e-01]
 [5.3295724e-02 9.4529241e-01 1.4119048e-03]
 [2.6925173e-01 6.7243609e-03 7.2402394e-01]
 [5.9112102e-01 5.4033268e-02 3.5484573e-01]
 [5.4224795e-01 3.8177039e-02 4.1957507e-01]
 [5.4773796e-02 9.4377053e-01 1.4557235e-03]
 [6.3890636e-01 7.7652201e-02 2.8344148e-01]
 [5.3844148e-01 3.8022544e-02 4.2353600e-01]
 [6.0790382e-02 9.3754697e-01 1.6626309e-03]
 [4.8197769e-02 9.5060539e-01 1.1967651e-03]
 [5.6899858e-01 4.4373017e-02 3.8662842e-01]
 [5.3079909e-01 3.6435295e-02 4.3276557e-01]
 [4.486652

In [135]:
sample = [[1,2,3,4]]
pred = model.predict(sample)
print(sample,'->',pred)

pred = model.predict(testSamples[10:14])
for p,t in zip(pred[0:4],testLabels[10:14]):
    print(p,"->",t)


[[1, 2, 3, 4]] -> [[0.19801329 0.00444155 0.7975451 ]]
[0.59663814 0.05513405 0.3482279 ] -> [1. 0. 0.]
[0.05329572 0.9452924  0.0014119 ] -> [0. 1. 0.]
[0.26925173 0.00672436 0.72402394] -> [0. 0. 1.]
[0.591121   0.05403327 0.35484573] -> [1. 0. 0.]


In [12]:
model.save('iris.h5')